"""Initialize

Revision ID: 3eba1a15e6e3
Revises: 
Create Date: 2021-07-18 20:30:11.089430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3eba1a15e6e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('values',
    sa.Column('value_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('value_id')
    )
    op.create_index(op.f('ix_values_name'), 'values', ['name'], unique=True)
    op.create_index(op.f('ix_values_timestamp'), 'values', ['timestamp'], unique=False)
    op.create_table('enterprises',
    sa.Column('enterprise_id', sa.GUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=140), nullable=True),
    sa.Column('symbol', sa.String(length=10), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('enterprise_id')
    )
    op.create_index(op.f('ix_enterprises_name'), 'enterprises', ['name'], unique=True)
    op.create_index(op.f('ix_enterprises_symbol'), 'enterprises', ['symbol'], unique=True)
    op.create_index(op.f('ix_enterprises_timestamp'), 'enterprises', ['timestamp'], unique=False)
    op.create_table('values_enterprises',
    sa.Column('value_id', sa.Integer(), nullable=True),
    sa.Column('enterprise_id', sa.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.enterprise_id'], ),
    sa.ForeignKeyConstraint(['value_id'], ['values.value_id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('values_enterprises')
    op.drop_index(op.f('ix_enterprises_timestamp'), table_name='enterprises')
    op.drop_index(op.f('ix_enterprises_symbol'), table_name='enterprises')
    op.drop_index(op.f('ix_enterprises_name'), table_name='enterprises')
    op.drop_table('enterprises')
    op.drop_index(op.f('ix_values_timestamp'), table_name='values')
    op.drop_index(op.f('ix_values_name'), table_name='values')
    op.drop_table('values')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
